### PR TITLE
Mssql support

### LINKED ISSUE #4: MS SQL Support
I would love to see MS SQL support. Let me know if you need any help. I can prob. set up a test database if needed.

### PR DESCRIPTION
**Pull request by edudutra**
Added MSSQL support. As commented on issue #4, still have to improve tests for MSSQL. Already added Win2012r2 vagrant box with SQL Express Install. Tests on Travis will fail. 

Additionally, I added a .gitattributes file so git can handle line terminations properly on windows so tests can run (and pass).

This closes #4.

### CODE REVIEW

**Comment by tmont** [comment]
Thanks for this. This looked brutal. I'm glad someone else figured this out :)

I had trouble running the mssql tests locally on node v0.12. After compiling node v0.10 I was able to connect and run them successfully. Can you list out your environment details (node version, virtualbox version, vagrant version, OS, etc.)? I want to put some details into the README.

Here's mine:

```
Ubuntu 14.10
Node v0.12.7
Virtualbox 4.3.18_Ubuntur96516
Vagrant 1.7.2
```

Again, I was able to connect once downgrading to node v0.10.39 (latest v0.10 release).

I'm just going to disable the mssql tests on travis, and locally as well if they're using an incompatible node version.

Not sure if it's related, but I put a comment in https://github.com/patriksimek/node-mssql/issues/181 as well.

**Comment by edudutra** [comment]
Well, that is strange. 

I've tested in the following environments:

```
Mac OS X Yosemite
Node v0.12.7 and  v0.10.39 / iojs (changing via nvm)
Vagrant 1.7.4
VirtualBox 5.0.0
```

```
Windows 8.1 (and Windows 10 after upgrade)
Node v0.12.7 and  v0.10.39 / iojs (changing via nvmw)
Vagrant 1.7.4
VirtualBox 5.0.0
```

```
Linux Mint 17.2  (inside VirtualBox)
Node v0.12.7 and  v0.10.39 / iojs (changing via nvm)
Connected to MSSQL in host
```

All of these worked just fine.

If I can help with anything else just let me know.

**Comment by tmont** [comment]
Sorry for being so lazy about merging this. I've been traveling among other things, and hadn't had time to test this out some more.

Based on your feedback, I'm just going to assume the segfault is some weird thing with my environment. I even manually compiled node 0.12.7 to see if that helped, but it did not. Not sure what the deal is.

Anyway, I merged in your PR manually and published to NPM (v`1.1.0`). I configured Travis to ignore the MSSQL tests, as Travis doesn't support Windows yet anyway.

Again, thanks for all the work on this. It looked annoying. :)

**Comment by edudutra** [comment]
That's awesome. Glad you could figure out a way to merge this.

**Pull request merged**
